### ISSUE TITLE
Additional validation

### ISSUE THREAD

**Issue by cboettig** [cboettig/emld#25]
EML validation imposes additional constraints beyond the XML schema validation.  I believe these can be summarized as follows: 

- [ ] combination of `id`+system attributes on any element should be unique.
- [x]  an element cannot have both child element `<references>`/`<describes>` and an attribute called `id`.
- [x] semantic `annotation` needs a subject: either from the `id` of its parent or as a child `<references>` of the annotation, but not both!

`eml_validate()` should enforce both of these conditions as well.  (Should be possible as simple xpath?)

Migrated from https://github.com/ropensci/EML/issues/244.

**Comment by mbjones** [comment]
The validation rules in EML are now clearly listed here:  https://github.com/NCEAS/eml/blob/BRANCH_EML_2_2/docs/eml-validation-refs.md

That document will be part of the EML 2.2.0 release specification.

**Comment by cboettig** [comment]
closed by #26
